env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
language: ruby
rvm:
  - 2.2
before_install:
- gem install simplecov  
before_script:
  - bundle install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - rubocop --fail-level=W
  - rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  hipchat:
    rooms:
      secure: DVMCsQCZ8423LAv6S4qd0d//7Rks/YeWhWDFfJNCoJUz2ilYnnZgjrwcwBecEaymW5AcpPrGO7Bu0Kls+S0qnm91drCm7XdDVRm59aY4YTUQ3zyjPO4Ntdd2njP36G3+/LtmRlKaJOLfXWmCkuTG4jBdMOjmvwLagMgRdrcW9Xs=
    template:
    - '<a href="https://travis-ci.org/%{repository}/builds/%{build_id}">%{repository}
      Build %{build_number}</a> on branch <i>%{branch}</i> by %{author}: <strong>%{message}</strong>
      <a href="https://github.com/%{repository}/commits/%{commit}">View on GitHub</a>'
    format: html
